
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  type UnencryptedL2Log,
  type Wallet,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import KernelAccountContractArtifactJson from '../../contracts/account/target/kernel_account-KernelAccount.json' assert { type: 'json' };
export const KernelAccountContractArtifact = loadContractArtifact(KernelAccountContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract KernelAccount;
 */
export class KernelAccountContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, KernelAccountContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, KernelAccountContract.artifact, wallet) as Promise<KernelAccountContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, authenticator: AztecAddressLike, signing_pubkeys: FieldLike[]) {
    return new DeployMethod<KernelAccountContract>(Fr.ZERO, wallet, KernelAccountContractArtifact, KernelAccountContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet, authenticator: AztecAddressLike, signing_pubkeys: FieldLike[]) {
    return new DeployMethod<KernelAccountContract>(publicKeysHash, wallet, KernelAccountContractArtifact, KernelAccountContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof KernelAccountContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<KernelAccountContract['methods'][M]>
  ) {
    return new DeployMethod<KernelAccountContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      KernelAccountContractArtifact,
      KernelAccountContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return KernelAccountContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'authenticators' | 'nonce'> {
      return {
        authenticators: {
      slot: new Fr(1n),
    },
nonce: {
      slot: new Fr(2n),
    }
      } as ContractStorageLayout<'authenticators' | 'nonce'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'AuthenticatorNote' | 'ValueNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(2232136525),
        },
AuthenticatorNote: {
          id: new NoteSelector(877655895),
        },
ValueNote: {
          id: new NoteSelector(1038582377),
        }
    } as ContractNotes<'AddressNote' | 'AuthenticatorNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, serialized_note: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(authenticator: struct, signing_pubkeys: array) */
    constructor: ((authenticator: AztecAddressLike, signing_pubkeys: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** entrypoint(app_payload: struct, fee_payload: struct, cancellable: boolean) */
    entrypoint: ((app_payload: { function_calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, is_static: boolean }[], nonce: FieldLike }, fee_payload: { function_calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, is_static: boolean }[], nonce: FieldLike, is_fee_payer: boolean }, cancellable: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_nonce() */
    get_nonce: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** install_authenticator(authenticator_address: struct, signing_pubkeys: array) */
    install_authenticator: ((authenticator_address: AztecAddressLike, signing_pubkeys: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_authenticator_installed(authenticator: struct) */
    is_authenticator_installed: ((authenticator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** uninstall_authenticator(authenticator_address: struct) */
    uninstall_authenticator: ((authenticator_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_private_authwit(inner_hash: field) */
    verify_private_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
