
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  ContractStorageLayout,
  ContractNotes,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  loadContractArtifact,
  NoirCompiledContract,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
} from '@aztec/aztec.js';
import EddsaBjjModuleContractArtifactJson from '../../contracts/validators/eddsa-bjj/target/eddsa_bjj_validator-EddsaBjjModule.json' assert { type: 'json' };
export const EddsaBjjModuleContractArtifact = loadContractArtifact(EddsaBjjModuleContractArtifactJson as NoirCompiledContract);

/**
 * Type-safe interface for contract EddsaBjjModule;
 */
export class EddsaBjjModuleContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, EddsaBjjModuleContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, EddsaBjjModuleContract.artifact, wallet) as Promise<EddsaBjjModuleContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<EddsaBjjModuleContract>(Fr.ZERO, wallet, EddsaBjjModuleContractArtifact, EddsaBjjModuleContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet, ) {
    return new DeployMethod<EddsaBjjModuleContract>(publicKeysHash, wallet, EddsaBjjModuleContractArtifact, EddsaBjjModuleContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof EddsaBjjModuleContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<EddsaBjjModuleContract['methods'][M]>
  ) {
    return new DeployMethod<EddsaBjjModuleContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      EddsaBjjModuleContractArtifact,
      EddsaBjjModuleContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return EddsaBjjModuleContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'public_keys'> {
      return {
        public_keys: {
      slot: new Fr(1n),
      typ: "Map<AztecAddress, PrivateMutable<PublicKeyNote, Context>, Context>",
    }
      } as ContractStorageLayout<'public_keys'>;
    }
    

  public static get notes(): ContractNotes<'PublicKeyNote'> {
    return {
      PublicKeyNote: {
          id: new Fr(8011798108105997510112178111116101n),
        }
    } as ContractNotes<'PublicKeyNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public override methods!: {
    
    /** uninstall() */
    uninstall: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_new_public_key(pub_key_x: field, pub_key_y: field) */
    set_new_public_key: ((pub_key_x: FieldLike, pub_key_y: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** validate(mode: field, outer_hash: field) */
    validate: ((mode: FieldLike, outer_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, serialized_note: array) */
    compute_note_hash_and_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, serialized_note: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_public_keys(account: struct) */
    view_public_keys: ((account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_installed(account: struct) */
    is_installed: ((account: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** install(keys: array) */
    install: ((keys: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
