[package]
name = "ecdsa_p256_validator"
type = "contract"
authors = ["porco"]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.56.0', directory = 'noir-projects/aztec-nr/aztec' }
authwit = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.56.0', directory = 'noir-projects/aztec-nr/authwit' }
helper = { path = '../../libs/helper' }
notes = { path = '../../libs/notes' }